alert("About to show intial state");
const months = ["Jan", "Feb", "Mar", "Apr"];
alert(months);
alert("About to begin modification");
const spliced = months.toSpliced(1, 2);
alert("Modification happened");
alert("About to show the output of toSpliced()");
alert(spliced);
alert("About to show final state of Array");
alert(months);
alert("Code finished");